name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test
      
      - name: Unit tests refactoring
        run: npm run test-refactoring
        
      - name: Merge lcov
        if: ${{ matrix.node-version == '10.x' && runner.OS == 'ubuntu-latest' }}
        run: npm run merge-lcov
        
      - name: Sonar scanner
        if: ${{ matrix.node-version == '10.x' && runner.OS == 'ubuntu-latest' }}
        run: ./node_modules/.bin/sonar-scanner
        
      - name: Sonarcloud
        if: ${{ matrix.node-version == '10.x' && runner.OS == 'ubuntu-latest' }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Angular expo test
        if: ${{ matrix.node-version == '12.x' }}
        run: npm run angularexpo
      
  e2e:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      
      - uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: E2E tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run saucelabs-test-e2e-mocha
